/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;
import javax.swing.table.DefaultTableModel;
import controle.LivroCon;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo..Aluno;
/**
 *
 * @author Michelly
 */
public class ConsultaLivro extends javax.swing.JFrame {
private void  atualizaTabela(){
LivroCon controle = new LivroCon();
        ArrayList<Livro> lista = new ArrayList<>();
        lista = controle.consultarLivros();
        DefaultTableModel tbm = (DefaultTableModel) tbLivros.getModel(); // Armazena a tabela da tela
            while(tbm.getRowCount() > 0){
            	tbm.removeRow(0);       
         }
         int i = 0;
        for(Livro liv : lista){
            tbm.addRow(new String[i]);
            tbLivros.setValueAt(liv.getId(), i, 0);
            tbLivros.setValueAt(liv.getTitulo(), i, 1);
            tbLivros.setValueAt(liv.getPaginas(), i, 2);
            tbLivros.setValueAt(liv.getValor(), i, 3);
            i++;
        }
}
    /**
     * Creates new form Aparecer
     */
    public ConsultaLivro() {
        initComponents();
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbpesquisaNome = new javax.swing.JLabel();
        tfpesquisaNome = new javax.swing.JTextField();
        btnpesquisaNome = new javax.swing.JButton();
        lbpesquisaId = new javax.swing.JLabel();
        PsId = new javax.swing.JTextField();
        btnpesquisaId = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLivros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVoltar = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbpesquisaNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbpesquisaNome.setText("Pesquisar por nome");

        tfpesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpesquisaNomeActionPerformed(evt);
            }
        });

        btnpesquisaNome.setBackground(new java.awt.Color(0, 0, 0));
        btnpesquisaNome.setForeground(new java.awt.Color(255, 255, 255));
        btnpesquisaNome.setText("Pesquisar");
        btnpesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisaNomeActionPerformed(evt);
            }
        });

        lbpesquisaId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbpesquisaId.setText("Pesquisar por ID");

        PsId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsIdActionPerformed(evt);
            }
        });

        btnpesquisaId.setBackground(new java.awt.Color(0, 0, 0));
        btnpesquisaId.setForeground(new java.awt.Color(255, 255, 255));
        btnpesquisaId.setText("Pesquisar");
        btnpesquisaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisaIdActionPerformed(evt);
            }
        });

        tbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Qnt:Páginas", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLivros.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                tbLivrosAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tbLivros);

        btnVoltar.setText("Voltar");
        btnVoltar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                btnVoltarMenuSelected(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnVoltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbpesquisaNome)
                            .addComponent(lbpesquisaId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PsId, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfpesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnpesquisaId, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(btnpesquisaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PsId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
         
           
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tfpesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpesquisaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpesquisaNomeActionPerformed

    private void btnpesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaNomeActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnpesquisaNomeActionPerformed

    private void PsIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PsIdActionPerformed

    private void btnpesquisaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaIdActionPerformed
        // TODO add your handling code here:        
        if(PsId.getText().equals("")){
           atualizaTabela();
          
        }else if(Integer.parseInt(PsId.getText()) > 0){
            AlunoCon controle = new AlunoCon();
            Livro livro = controle.consultarAluno(Integer.parseInt(PsId.getText()));
            DefaultTableModel tbm = (DefaultTableModel) tbLivros.getModel();
            			while(tbm.getRowCount() > 0){
                			tbm.removeRow(0);
                                }
                                tbm.addRow(new String[0]);
				tbLivros.setValueAt(livro.getId(),0,0);
            			tbLivros.setValueAt(livro.getTitulo(),0,1);
            			tbLivros.setValueAt(livro.getPaginas(),0,2);
            			tbLivros.setValueAt(livro.getValor(), 0, 3);
        }else{
            JOptionPane.showMessageDialog(null,"Valor inválido.","Programinha", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnpesquisaIdActionPerformed

    private void tbLivrosAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tbLivrosAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLivrosAncestorMoved

    private void btnVoltarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_btnVoltarMenuSelected
        // TODO add your handling code here:
        new Home().setVisible(true);
                    dispose(); // Fecha a Tela Login
        
    }//GEN-LAST:event_btnVoltarMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PsId;
    private javax.swing.JMenu btnVoltar;
    private javax.swing.JButton btnpesquisaId;
    private javax.swing.JButton btnpesquisaNome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbpesquisaId;
    private javax.swing.JLabel lbpesquisaNome;
    private javax.swing.JTable tbLivros;
    private javax.swing.JTextField tfpesquisaNome;
    // End of variables declaration//GEN-END:variables
}
