/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;
import javax.swing.table.DefaultTableModel;
import controle.LivroCon;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Livro;
/**
 *
 * @author Michelly
 */
public class RemoverLivro extends javax.swing.JFrame {
private void  atualizaTabela(){
LivroCon controle = new LivroCon();
        ArrayList<Livro> lista = new ArrayList<>();
        lista = controle.consultarLivros();
        DefaultTableModel tbm = (DefaultTableModel) tbLivros.getModel(); // Armazena a tabela da tela
            while(tbm.getRowCount() > 0){
            	tbm.removeRow(0);       
         }
         int i = 0;
        for(Livro liv : lista){
            tbm.addRow(new String[i]);
            tbLivros.setValueAt(liv.getId(), i, 0);
            tbLivros.setValueAt(liv.getTitulo(), i, 1);
            tbLivros.setValueAt(liv.getPaginas(), i, 2);
            tbLivros.setValueAt(liv.getValor(), i, 3);
            i++;
        }
}

    /**
     * Creates new form RemoverLivro
     */
    public RemoverLivro() {
        initComponents();
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbpesquisaId = new javax.swing.JLabel();
        IdExcluir = new javax.swing.JTextField();
        BtnId = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLivros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnVoltar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbpesquisaId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbpesquisaId.setText("Pesquisar por ID pra Remover:");

        IdExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdExcluirActionPerformed(evt);
            }
        });

        BtnId.setBackground(new java.awt.Color(0, 0, 0));
        BtnId.setForeground(new java.awt.Color(255, 255, 255));
        BtnId.setText("Pesquisar");
        BtnId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIdActionPerformed(evt);
            }
        });

        tbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Qnt:Páginas", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLivros.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                tbLivrosAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tbLivros);

        btnVoltar.setText("Voltar");
        btnVoltar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                btnVoltarMenuSelected(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jMenuBar1.add(btnVoltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbpesquisaId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BtnId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbpesquisaId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_btnVoltarMenuSelected
        // TODO add your handling code here
         new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarMenuSelected

    private void IdExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdExcluirActionPerformed

    private void BtnIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIdActionPerformed
        // TODO add your handling code here:
            Livro livro = new Livro();
            livro.setId(Integer.parseInt(IdExcluir.getText()));
            LivroCon controle = new LivroCon();
            
        if(IdExcluir.getText().equals("")){
            atualizaTabela();
        }else if(controle.deleteLivro(livro)){
               JOptionPane.showMessageDialog(null,"Erro Ao Excluir");
        }else{
            JOptionPane.showMessageDialog(null,"Excluido Com Sucesso");
            IdExcluir.setText("");
            atualizaTabela();
         
    }//GEN-LAST:event_BtnIdActionPerformed
    }
    private void tbLivrosAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tbLivrosAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLivrosAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnId;
    private javax.swing.JTextField IdExcluir;
    private javax.swing.JMenu btnVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbpesquisaId;
    private javax.swing.JTable tbLivros;
    // End of variables declaration//GEN-END:variables
}
